receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  awsemf:
    region: "us-east-1"
    log_group_name: "/aws/app/grafana-metrics"
    log_stream_name: "otel-stream"
    namespace: "Grafana/CustomMetrics"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]
