receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.us-east-1.amazonaws.com"
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [awsprometheusremotewrite, logging]
