AWSTemplateFormatVersion: '2010-09-09'
Description: 'Managed Grafana Workspace and Dashboard'

Resources:
  GrafanaWorkspace:
    Type: 'AWS::Grafana::Workspace'
    Properties:
      AccountAccessType: 'CURRENT_ACCOUNT'
      AuthenticationProviders: ['AWS_SSO']
      PermissionType: 'SERVICE_MANAGED'

  MyDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardName: 'Interview-Demo-Dashboard'
      DashboardBody: >
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [ [ "AWS/EC2", "CPUUtilization", "InstanceId", "i-1234567890abcdef0" ] ],
                "view": "timeSeries",
                "stacked": false,
                "title": "EC2 CPU Utilization"
              }
            }
          ]
        }
