AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal Managed Grafana Workspace

Resources:
  GrafanaWorkspaceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {Service: grafana.amazonaws.com}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ["cloudwatch:Describe*", "cloudwatch:Get*", "cloudwatch:List*"]
                Resource: "*"

  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders: [AWS_SSO]
      PermissionType: CUSTOMER_MANAGED
      WorkspaceRoleArn: !GetAtt GrafanaWorkspaceRole.Arn
      Name: ObservabilityStack
