receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  # AWS Managed Grafana/CloudWatch ke liye
  awsemf:
    log_group_name: "BusinessMetrics"
    log_stream_name: "otel-stream"
    dimension_rollup_option: "NoDimensionRollup"
  
  # Multi-cloud support ke liye OTLP (Vendor-neutral standard)
  otlp:
    endpoint: "tempo-backend-or-other-collector:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf, otlp]
