AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Managed Grafana Infrastructure'

Resources:
  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      PermissionType: SERVICE_MANAGED
      WorkspaceName: ObservabilityWorkspace

Outputs:
  WorkspaceId:
    Value: !Ref GrafanaWorkspace
    Description: 'ID of the created Grafana Workspace'
