name: Deploy Grafana Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::882352060841:role/GrafanaWorkspaceRole

      - name: Deploy Grafana Stack
        run: |
          aws cloudformation deploy \
            --template-file cfn/grafana.yaml \
            --stack-name grafana \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1

      - name: Deploy CloudWatch Stack
        run: |
          aws cloudformation deploy \
            --template-file cfn/cloudwatch.yaml \
            --stack-name cw \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1

      - name: Upload Dashboard and Alerts
        run: |
          aws cloudformation deploy \
            --template-file cfn/dashboard.yaml \
            --stack-name grafana-dashboard \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1
